### ISSUE TITLE
syntaxerror but i'm on python 3.8.0?

### ISSUE THREAD

**Issue by deviltuner** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#114]
hello

i receive:

`sudo python3 main.py
  File "<fstring>", line 1
    (announcement_coin=)
                      ^
SyntaxError: invalid syntax
`
but i thionk i'm on python 3.8.0
`pi@raspberrypi:~ $ python -V
Python 3.8.0`

please help thanks

**Comment by AussieTerror** [comment]
This is something invalid in the f'string {},   check your yaml's (config.yml and auth.yml)

**Comment by gutster95** [comment]
You start the script with `python3` but you use only `python` for the version info. Try to use only `python` to run the main.py. Could also verify that by just typing `python3` into cmd and see what version is shown

**Comment by deviltuner** [comment]
Oh noob.... Perfect python3 not World python work... I'm si stupide sory about that 😫

**Comment by Linus045** [comment]
`python` and `python3` both point to a specific python installation in your case.
You can use the `where` command (`where python3 python`) to figure out where they point to.

Both are valid to use and will start the script, you just need to be sure which python version is used.
(To figure that out run `python --version` or `python3 --version`)
If you use Python 3.7 the syntax error is correct since the fstring syntax '{someVar=}' was first introduced in Python 3.8.
You need therefore Python version 3.8 or higher to run the bot.
